import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./navbar";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by darel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='text-white bg-white font-mono'
      >
        <div className="gap-4">
          <div>
            <NavBar/>
          </div>
          {children}
          <div className="mt-0">
          <Footer/>
          </div>
        </div>
        
      </body>
    </html>
  );
}
